export enum OperationType {
  'CREAR_DEUDA' = 1,
  'CREAR_NOTA_CREDITO' = 2,
  'CREAR_NOTA_DEBITO' = 2,
  'CREAR_AJUSTE_SALDO' = 3,
  'CREAR_PAGO_DIRECTO' = 6,
  'CREAR_PAGO_CTA_CTE' = 7,
  'CREAR_PAGO_TRANSF_LOTE' = 15,
  'CREAR_DEPOSITO' = 16,
  'CREAR_TRANSFERENCIA' = 17,
  'CREAR_SALDO_CAJA' = 18,
  'CREAR_ANTICIPO' = 19,

  'GET_DEUDA' = 8,
  'GET_NOTA_DEBITO' = 9,
  'GET_NOTA_CREDITO' = 10,
  'GET_PAGO' = 13,
  'GET_ANTICIPO' = 14,

  'GET_ENTE_DEUDA' = 11,
  'GET_ENTE_NOTA_CREDITO' = 12,

  'EDITAR_DEUDA' = 4,
  'EDITAR_NOTA_CREDITO' = 5,
  'EDITAR_NOTA_DEBITO' = 5,
}
