name: Application CI
on: [push, pull_request]
jobs:
    pipeline:
        name: ErpSep pipeline
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
        timeout-minutes: 40
        env:
            NODE_VERSION: 14.16.0
            JHI_DISABLE_WEBPACK_LOGS: true
            NG_CLI_ANALYTICS: false
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.16.0
            - name: Install node.js packages
              run: npm install
            - name: Package application
              run: npm run build
            - name: 'E2E: Package'
              run: npm run ci:e2e:package
            - name: 'E2E: Prepare'
              run: npm run ci:e2e:prepare
            - name: 'E2E: Run'
              run: npm run ci:e2e:run
              env:
                CYPRESS_ENABLE_RECORD: false
                CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
                CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            - name: 'E2E: Teardown'
              run: npm run ci:e2e:teardown
